### PR TITLE
Replace infinite while with for loop

### LINKED ISSUE #12: Why is the training loop an infinite loop?
Maybe this question is silly, but I do not get why the training loop is "while 1". Why wouldn't that train  for an infinite number of times?

### PR DESCRIPTION
**Pull request by MatthewScholefield**
This fixes #12

### CODE REVIEW

**Comment by MatthewScholefield** [comment]
@llSourcell Ping

**Comment by hcchengithub** [comment]
This pull-request should be rejected. Close but incorrect.

**Comment by MatthewScholefield** [comment]
@hcchengithub You could give a reason so that it could be changed.

Perhaps your talking about how it still does 10 epochs per iteration and you were thinking it'd make more sense to just put `n_epoch=training_iters`.

**Comment by MatthewScholefield** [comment]
Closing due to lack of response.

**Pull request closed without merging**
